import type {
  Institution, User, Club, Event, Venue,
  SportsLeague, SportsTeam, SportsGame,
  WellnessCheckin, Notification, AnalyticsData
} from '../types';

export const MOCK_INSTITUTION: Institution = {
  id: 'inst-uoft',
  name: 'University of Toronto',
  domain: 'utoronto.ca',
  plan: 'growth',
  studentCount: 89000,
};

export const MOCK_USERS: User[] = [
  {
    id: 'user-student-1',
    email: 'student@demo.com',
    name: 'Alex Kim',
    role: 'student',
    institutionId: 'inst-uoft',
    avatarUrl: '',
    bio: 'Computer Science sophomore. Interested in robotics and photography.',
    interests: ['Robotics', 'Photography', 'Basketball', 'Coding'],
    joinedAt: '2024-09-01',
  },
  {
    id: 'user-admin-1',
    email: 'admin@demo.com',
    name: 'Dr. Sarah Patel',
    role: 'admin',
    institutionId: 'inst-uoft',
    avatarUrl: '',
    bio: 'Dean of Student Life at University of Toronto.',
    interests: [],
    joinedAt: '2023-01-15',
  },
  {
    id: 'user-coach-1',
    email: 'coach@demo.com',
    name: 'Marcus Thompson',
    role: 'coach',
    institutionId: 'inst-uoft',
    avatarUrl: '',
    bio: 'Intramural Sports Coordinator. Former varsity basketball player.',
    interests: ['Basketball', 'Soccer', 'Fitness'],
    joinedAt: '2022-08-20',
  },
  {
    id: 'user-club-1',
    email: 'club@demo.com',
    name: 'Priya Sharma',
    role: 'club_leader',
    institutionId: 'inst-uoft',
    avatarUrl: '',
    bio: 'President of Photography Society and Sustainability Club.',
    interests: ['Photography', 'Sustainability', 'Film'],
    joinedAt: '2023-09-05',
  },
  {
    id: 'user-teacher-1',
    email: 'teacher@demo.com',
    name: 'Prof. James Crawford',
    role: 'teacher',
    institutionId: 'inst-uoft',
    avatarUrl: '',
    bio: 'Professor of Computer Science. 15+ years of teaching experience.',
    interests: ['Algorithms', 'AI', 'Teaching'],
    joinedAt: '2020-08-15',
  },
  {
    id: 'user-it-1',
    email: 'it@demo.com',
    name: 'Leon Okafor',
    role: 'it_director',
    institutionId: 'inst-uoft',
    avatarUrl: '',
    bio: 'IT Director. Responsible for all technology systems and integrations.',
    interests: ['Security', 'Cloud', 'Automation'],
    joinedAt: '2021-01-10',
  },
  {
    id: 'user-parent-1',
    email: 'parent@demo.com',
    name: 'Jennifer Lawson',
    role: 'parent',
    institutionId: 'inst-uoft',
    avatarUrl: '',
    bio: 'Parent of Emma Lawson. Sunshine Preschool.',
    interests: [],
    joinedAt: '2025-09-01',
  },
];

export const MOCK_CLUBS: Club[] = [
  {
    id: 'club-1',
    name: 'Photography Society',
    category: 'Arts & Culture',
    description: 'Explore photography through workshops, exhibitions, and field trips across the city.',
    memberCount: 142,
    leaderId: 'user-club-1',
    institutionId: 'inst-uoft',
    coverGradient: 'linear-gradient(135deg, #0047AB 0%, #759eff 100%)',
    iconBg: '#D6E4FF',
    tags: ['Creative', 'Workshops', 'Exhibition'],
    isActive: true,
    createdAt: '2023-09-10',
  },
  {
    id: 'club-2',
    name: 'Robotics Club',
    category: 'STEM',
    description: 'Build, program, and compete with robots. From beginners to advanced engineers welcome.',
    memberCount: 98,
    leaderId: 'user-student-1',
    institutionId: 'inst-uoft',
    coverGradient: 'linear-gradient(135deg, #FF7F50 0%, #ffb08a 100%)',
    iconBg: '#FFE4D9',
    tags: ['Engineering', 'Competition', 'Innovation'],
    isActive: true,
    createdAt: '2023-09-12',
  },
  {
    id: 'club-3',
    name: 'Debate Team',
    category: 'Academic',
    description: 'Sharpen critical thinking and public speaking through competitive debate tournaments.',
    memberCount: 64,
    leaderId: 'user-student-1',
    institutionId: 'inst-uoft',
    coverGradient: 'linear-gradient(135deg, #00A86B 0%, #5de0b0 100%)',
    iconBg: '#C8F5E2',
    tags: ['Public Speaking', 'Competition', 'Leadership'],
    isActive: true,
    createdAt: '2023-09-15',
  },
  {
    id: 'club-4',
    name: 'Basketball IM',
    category: 'Sports',
    description: 'Intramural basketball league for all skill levels. Fun, competitive, and social.',
    memberCount: 210,
    leaderId: 'user-coach-1',
    institutionId: 'inst-uoft',
    coverGradient: 'linear-gradient(135deg, #7B2D8B 0%, #c48fd4 100%)',
    iconBg: '#EFD9F5',
    tags: ['Sports', 'Recreation', 'Team'],
    isActive: true,
    createdAt: '2023-09-01',
  },
  {
    id: 'club-5',
    name: 'International Students',
    category: 'Community',
    description: 'Celebrate diversity, connect cultures, and support international students at UofT.',
    memberCount: 387,
    leaderId: 'user-admin-1',
    institutionId: 'inst-uoft',
    coverGradient: 'linear-gradient(135deg, #E91E63 0%, #f48fb1 100%)',
    iconBg: '#FCE4EC',
    tags: ['Cultural', 'Community', 'Support'],
    isActive: true,
    createdAt: '2023-09-08',
  },
  {
    id: 'club-6',
    name: 'Coding Collective',
    category: 'STEM',
    description: 'Hackathons, open-source projects, and coding challenges. All languages welcome.',
    memberCount: 156,
    leaderId: 'user-student-1',
    institutionId: 'inst-uoft',
    coverGradient: 'linear-gradient(135deg, #1565C0 0%, #42A5F5 100%)',
    iconBg: '#E3F2FD',
    tags: ['Hackathon', 'Open Source', 'Tech'],
    isActive: true,
    createdAt: '2023-09-20',
  },
  {
    id: 'club-7',
    name: 'Film Society',
    category: 'Arts & Culture',
    description: 'Weekly screenings, film analysis, and student filmmaking projects.',
    memberCount: 89,
    leaderId: 'user-club-1',
    institutionId: 'inst-uoft',
    coverGradient: 'linear-gradient(135deg, #37474F 0%, #90A4AE 100%)',
    iconBg: '#ECEFF1',
    tags: ['Cinema', 'Creative', 'Screenings'],
    isActive: true,
    createdAt: '2023-09-18',
  },
  {
    id: 'club-8',
    name: 'Sustainability Club',
    category: 'Environmental',
    description: 'Campus greening initiatives, zero-waste workshops, and environmental advocacy.',
    memberCount: 203,
    leaderId: 'user-club-1',
    institutionId: 'inst-uoft',
    coverGradient: 'linear-gradient(135deg, #00A86B 0%, #A5D6A7 100%)',
    iconBg: '#C8F5E2',
    tags: ['Environment', 'Activism', 'Green'],
    isActive: true,
    createdAt: '2023-09-25',
  },
];

export const MOCK_VENUES: Venue[] = [
  {
    id: 'venue-1',
    name: 'Bahen Centre 201',
    building: 'Bahen Centre for Information Technology',
    capacity: 60,
    amenities: ['Projector', 'Whiteboard', 'WiFi', 'AC'],
    isBookable: true,
    institutionId: 'inst-uoft',
  },
  {
    id: 'venue-2',
    name: 'Hart House Great Hall',
    building: 'Hart House',
    capacity: 400,
    amenities: ['Stage', 'Sound System', 'Catering', 'WiFi'],
    isBookable: true,
    institutionId: 'inst-uoft',
  },
  {
    id: 'venue-3',
    name: 'Athletic Centre Court 1',
    building: 'Athletic Centre',
    capacity: 200,
    amenities: ['Changerooms', 'Bleachers', 'Scoreboard'],
    isBookable: true,
    institutionId: 'inst-uoft',
  },
  {
    id: 'venue-4',
    name: 'Robarts Library Study Room',
    building: 'Robarts Library',
    capacity: 12,
    amenities: ['Whiteboard', 'WiFi', 'Monitor'],
    isBookable: true,
    institutionId: 'inst-uoft',
  },
  {
    id: 'venue-5',
    name: 'Convocation Hall',
    building: 'Convocation Hall',
    capacity: 1740,
    amenities: ['Stage', 'Lighting', 'Sound System', 'Streaming'],
    isBookable: false,
    institutionId: 'inst-uoft',
  },
];

export const MOCK_EVENTS: Event[] = [
  {
    id: 'event-1',
    title: 'Photography Exhibition: Urban Lens',
    description: 'Showcase student photography from the Fall semester. All welcome.',
    clubId: 'club-1',
    clubName: 'Photography Society',
    venueId: 'venue-2',
    venueName: 'Hart House Great Hall',
    startTime: '2026-04-05T14:00:00',
    endTime: '2026-04-05T20:00:00',
    category: 'Arts & Culture',
    capacity: 300,
    rsvpCount: 187,
    status: 'upcoming',
    coverGradient: 'linear-gradient(135deg, #0047AB 0%, #759eff 100%)',
    institutionId: 'inst-uoft',
  },
  {
    id: 'event-2',
    title: 'Robotics Hackathon 2026',
    description: '48-hour hackathon. Build robots, win prizes, make friends.',
    clubId: 'club-2',
    clubName: 'Robotics Club',
    venueId: 'venue-1',
    venueName: 'Bahen Centre 201',
    startTime: '2026-04-12T09:00:00',
    endTime: '2026-04-14T09:00:00',
    category: 'STEM',
    capacity: 60,
    rsvpCount: 54,
    status: 'upcoming',
    coverGradient: 'linear-gradient(135deg, #FF7F50 0%, #ffb08a 100%)',
    institutionId: 'inst-uoft',
  },
  {
    id: 'event-3',
    title: 'Campus Sustainability Fair',
    description: 'Booths, talks, and workshops on sustainable living.',
    clubId: 'club-8',
    clubName: 'Sustainability Club',
    venueId: 'venue-2',
    venueName: 'Hart House Great Hall',
    startTime: '2026-04-18T10:00:00',
    endTime: '2026-04-18T16:00:00',
    category: 'Environmental',
    capacity: 400,
    rsvpCount: 312,
    status: 'upcoming',
    coverGradient: 'linear-gradient(135deg, #00A86B 0%, #5de0b0 100%)',
    institutionId: 'inst-uoft',
  },
  {
    id: 'event-4',
    title: 'International Food Festival',
    description: 'Taste dishes from 40+ countries. Cultural performances included.',
    clubId: 'club-5',
    clubName: 'International Students',
    venueName: 'Front Campus',
    startTime: '2026-04-22T11:00:00',
    endTime: '2026-04-22T19:00:00',
    category: 'Community',
    capacity: 2000,
    rsvpCount: 1450,
    status: 'upcoming',
    coverGradient: 'linear-gradient(135deg, #E91E63 0%, #f48fb1 100%)',
    institutionId: 'inst-uoft',
  },
  {
    id: 'event-5',
    title: 'Coding Collective Hackathon',
    description: 'Build something cool in 24 hours. Prizes for best app, best design, and most impactful.',
    clubId: 'club-6',
    clubName: 'Coding Collective',
    venueId: 'venue-1',
    venueName: 'Bahen Centre 201',
    startTime: '2026-05-03T10:00:00',
    endTime: '2026-05-04T10:00:00',
    category: 'STEM',
    capacity: 60,
    rsvpCount: 41,
    status: 'upcoming',
    coverGradient: 'linear-gradient(135deg, #1565C0 0%, #42A5F5 100%)',
    institutionId: 'inst-uoft',
  },
  {
    id: 'event-6',
    title: 'Film Screening: Parasite',
    description: 'Weekly film club screening followed by a discussion.',
    clubId: 'club-7',
    clubName: 'Film Society',
    venueName: 'Innis Town Hall',
    startTime: '2026-03-27T19:00:00',
    endTime: '2026-03-27T22:00:00',
    category: 'Arts & Culture',
    capacity: 150,
    rsvpCount: 98,
    status: 'upcoming',
    coverGradient: 'linear-gradient(135deg, #37474F 0%, #90A4AE 100%)',
    institutionId: 'inst-uoft',
  },
  {
    id: 'event-7',
    title: 'Debate Championship Finals',
    description: 'Watch top debaters compete for the annual championship trophy.',
    clubId: 'club-3',
    clubName: 'Debate Team',
    venueName: 'Convocation Hall',
    startTime: '2026-03-20T15:00:00',
    endTime: '2026-03-20T18:00:00',
    category: 'Academic',
    capacity: 500,
    rsvpCount: 487,
    status: 'past',
    coverGradient: 'linear-gradient(135deg, #00A86B 0%, #5de0b0 100%)',
    institutionId: 'inst-uoft',
  },
  {
    id: 'event-8',
    title: 'Basketball Intramural Finals',
    description: 'Championship game between the top two teams.',
    clubId: 'club-4',
    clubName: 'Basketball IM',
    venueId: 'venue-3',
    venueName: 'Athletic Centre Court 1',
    startTime: '2026-03-15T14:00:00',
    endTime: '2026-03-15T17:00:00',
    category: 'Sports',
    capacity: 200,
    rsvpCount: 200,
    status: 'past',
    coverGradient: 'linear-gradient(135deg, #7B2D8B 0%, #c48fd4 100%)',
    institutionId: 'inst-uoft',
  },
  {
    id: 'event-9',
    title: 'Mental Health Awareness Week Kickoff',
    description: 'Opening ceremony with speakers, resources, and community activities.',
    venueName: 'Hart House',
    startTime: '2026-04-07T12:00:00',
    endTime: '2026-04-07T15:00:00',
    category: 'Wellness',
    capacity: 300,
    rsvpCount: 156,
    status: 'upcoming',
    coverGradient: 'linear-gradient(135deg, #9C27B0 0%, #CE93D8 100%)',
    institutionId: 'inst-uoft',
  },
  {
    id: 'event-10',
    title: 'Spring Career Fair',
    description: 'Meet 80+ employers. Internships, co-ops, and full-time roles.',
    venueName: 'Convocation Hall',
    startTime: '2026-04-02T10:00:00',
    endTime: '2026-04-02T16:00:00',
    category: 'Academic',
    capacity: 1740,
    rsvpCount: 1200,
    status: 'upcoming',
    coverGradient: 'linear-gradient(135deg, #0047AB 0%, #759eff 100%)',
    institutionId: 'inst-uoft',
  },
];

export const MOCK_LEAGUES: SportsLeague[] = [
  {
    id: 'league-1',
    name: 'Soccer Intramurals Fall 2025',
    sport: 'Soccer',
    season: 'Fall 2025',
    status: 'completed',
    institutionId: 'inst-uoft',
    startDate: '2025-09-10',
    endDate: '2025-12-05',
  },
  {
    id: 'league-2',
    name: 'Basketball Intramurals Winter 2026',
    sport: 'Basketball',
    season: 'Winter 2026',
    status: 'active',
    institutionId: 'inst-uoft',
    startDate: '2026-01-15',
    endDate: '2026-04-30',
  },
];

export const MOCK_TEAMS: SportsTeam[] = [
  // Soccer teams
  { id: 'team-s1', name: 'FC Bahen', leagueId: 'league-1', wins: 8, losses: 2, draws: 1, points: 25, goalsFor: 24, goalsAgainst: 10 },
  { id: 'team-s2', name: 'Robarts Rovers', leagueId: 'league-1', wins: 7, losses: 2, draws: 2, points: 23, goalsFor: 20, goalsAgainst: 12 },
  { id: 'team-s3', name: 'Hart House United', leagueId: 'league-1', wins: 6, losses: 4, draws: 1, points: 19, goalsFor: 18, goalsAgainst: 15 },
  { id: 'team-s4', name: 'Sid Smith FC', leagueId: 'league-1', wins: 4, losses: 5, draws: 2, points: 14, goalsFor: 14, goalsAgainst: 18 },
  { id: 'team-s5', name: 'Myhal Rangers', leagueId: 'league-1', wins: 3, losses: 6, draws: 2, points: 11, goalsFor: 11, goalsAgainst: 21 },
  { id: 'team-s6', name: 'Victoria Vanguard', leagueId: 'league-1', wins: 1, losses: 9, draws: 1, points: 4, goalsFor: 6, goalsAgainst: 28 },
  // Basketball teams
  { id: 'team-b1', name: 'Dunk Collective', leagueId: 'league-2', wins: 9, losses: 1, draws: 0, points: 27 },
  { id: 'team-b2', name: 'Three Point Scholars', leagueId: 'league-2', wins: 7, losses: 3, draws: 0, points: 21 },
  { id: 'team-b3', name: 'Athletic Aces', leagueId: 'league-2', wins: 6, losses: 4, draws: 0, points: 18 },
  { id: 'team-b4', name: 'Bahen Ballers', leagueId: 'league-2', wins: 5, losses: 5, draws: 0, points: 15 },
  { id: 'team-b5', name: 'Innis Hoopers', leagueId: 'league-2', wins: 3, losses: 7, draws: 0, points: 9 },
  { id: 'team-b6', name: 'Robarts Rim Busters', leagueId: 'league-2', wins: 1, losses: 9, draws: 0, points: 3 },
];

export const MOCK_GAMES: SportsGame[] = [
  { id: 'game-1', leagueId: 'league-2', homeTeamId: 'team-b1', homeTeamName: 'Dunk Collective', awayTeamId: 'team-b2', awayTeamName: 'Three Point Scholars', homeScore: 82, awayScore: 74, scheduledAt: '2026-03-10T18:00:00', status: 'completed', venue: 'Athletic Centre Court 1' },
  { id: 'game-2', leagueId: 'league-2', homeTeamId: 'team-b3', homeTeamName: 'Athletic Aces', awayTeamId: 'team-b4', awayTeamName: 'Bahen Ballers', homeScore: 68, awayScore: 71, scheduledAt: '2026-03-12T19:00:00', status: 'completed', venue: 'Athletic Centre Court 1' },
  { id: 'game-3', leagueId: 'league-2', homeTeamId: 'team-b1', homeTeamName: 'Dunk Collective', awayTeamId: 'team-b3', awayTeamName: 'Athletic Aces', homeScore: 77, awayScore: 60, scheduledAt: '2026-03-17T18:00:00', status: 'completed', venue: 'Athletic Centre Court 1' },
  { id: 'game-4', leagueId: 'league-2', homeTeamId: 'team-b2', homeTeamName: 'Three Point Scholars', awayTeamId: 'team-b5', awayTeamName: 'Innis Hoopers', homeScore: 88, awayScore: 55, scheduledAt: '2026-03-19T19:00:00', status: 'completed', venue: 'Athletic Centre Court 1' },
  { id: 'game-5', leagueId: 'league-2', homeTeamId: 'team-b1', homeTeamName: 'Dunk Collective', awayTeamId: 'team-b4', awayTeamName: 'Bahen Ballers', scheduledAt: '2026-03-24T18:00:00', status: 'live', venue: 'Athletic Centre Court 1' },
  { id: 'game-6', leagueId: 'league-2', homeTeamId: 'team-b2', homeTeamName: 'Three Point Scholars', awayTeamId: 'team-b3', awayTeamName: 'Athletic Aces', scheduledAt: '2026-03-26T19:00:00', status: 'scheduled', venue: 'Athletic Centre Court 1' },
  { id: 'game-7', leagueId: 'league-2', homeTeamId: 'team-b4', homeTeamName: 'Bahen Ballers', awayTeamId: 'team-b5', awayTeamName: 'Innis Hoopers', scheduledAt: '2026-03-31T18:00:00', status: 'scheduled', venue: 'Athletic Centre Court 1' },
  { id: 'game-8', leagueId: 'league-2', homeTeamId: 'team-b1', homeTeamName: 'Dunk Collective', awayTeamId: 'team-b2', awayTeamName: 'Three Point Scholars', scheduledAt: '2026-04-07T19:00:00', status: 'scheduled', venue: 'Athletic Centre Court 1' },
];

export const MOCK_ANALYTICS: AnalyticsData = {
  totalStudents: 89000,
  activeStudents: 67200,
  atRiskStudents: 47,
  totalClubs: 142,
  totalEvents: 38,
  wellnessAvg: 3.6,
  weeklyTrend: [
    { week: 'Jan 27', activeUsers: 52000, newSignups: 420, eventsCreated: 12 },
    { week: 'Feb 3', activeUsers: 55400, newSignups: 380, eventsCreated: 15 },
    { week: 'Feb 10', activeUsers: 58900, newSignups: 520, eventsCreated: 18 },
    { week: 'Feb 17', activeUsers: 61200, newSignups: 310, eventsCreated: 14 },
    { week: 'Feb 24', activeUsers: 59800, newSignups: 290, eventsCreated: 16 },
    { week: 'Mar 3', activeUsers: 63400, newSignups: 450, eventsCreated: 22 },
    { week: 'Mar 10', activeUsers: 65100, newSignups: 390, eventsCreated: 19 },
    { week: 'Mar 17', activeUsers: 67200, newSignups: 410, eventsCreated: 21 },
  ],
  clubsByCategory: [
    { category: 'STEM', count: 34, color: '#0047AB' },
    { category: 'Arts & Culture', count: 28, color: '#FF7F50' },
    { category: 'Sports', count: 22, color: '#00A86B' },
    { category: 'Community', count: 19, color: '#9C27B0' },
    { category: 'Academic', count: 17, color: '#1565C0' },
    { category: 'Environmental', count: 11, color: '#2E7D32' },
    { category: 'Wellness', count: 7, color: '#E91E63' },
    { category: 'Other', count: 4, color: '#78909C' },
  ],
  topClubs: [
    { id: 'club-5', name: 'International Students', members: 387, events: 12, growth: 18 },
    { id: 'club-4', name: 'Basketball IM', members: 210, events: 8, growth: 12 },
    { id: 'club-8', name: 'Sustainability Club', members: 203, events: 15, growth: 31 },
    { id: 'club-6', name: 'Coding Collective', members: 156, events: 10, growth: 22 },
    { id: 'club-1', name: 'Photography Society', members: 142, events: 9, growth: 8 },
    { id: 'club-2', name: 'Robotics Club', members: 98, events: 6, growth: 14 },
  ],
};

export const MOCK_NOTIFICATIONS: Notification[] = [
  { id: 'notif-1', userId: 'user-student-1', title: 'Event Reminder', body: 'Photography Exhibition starts in 2 hours at Hart House Great Hall.', type: 'event', isRead: false, createdAt: '2026-03-24T12:00:00' },
  { id: 'notif-2', userId: 'user-student-1', title: 'Club Update', body: 'Robotics Club posted a new meeting schedule for April.', type: 'club', isRead: false, createdAt: '2026-03-23T09:30:00' },
  { id: 'notif-3', userId: 'user-student-1', title: 'Sports Result', body: 'Dunk Collective won 82-74 vs Three Point Scholars!', type: 'sports', isRead: true, createdAt: '2026-03-22T20:15:00' },
  { id: 'notif-4', userId: 'user-student-1', title: 'Wellness Check', body: 'You\'ve maintained a 5-day wellness streak! Keep it up.', type: 'wellness', isRead: true, createdAt: '2026-03-21T08:00:00' },
  { id: 'notif-5', userId: 'user-student-1', title: 'New Event', body: 'Sustainability Club is hosting a Campus Fair on Apr 18.', type: 'event', isRead: false, createdAt: '2026-03-20T14:00:00' },
  { id: 'notif-6', userId: 'user-student-1', title: 'Club Invite', body: 'You\'ve been invited to join Film Society by Priya Sharma.', type: 'club', isRead: false, createdAt: '2026-03-19T11:00:00' },
  { id: 'notif-7', userId: 'user-student-1', title: 'Game Tonight', body: 'Live game: Dunk Collective vs Bahen Ballers at 6PM.', type: 'sports', isRead: false, createdAt: '2026-03-24T09:00:00' },
  { id: 'notif-8', userId: 'user-student-1', title: 'System Update', body: 'Campus Tribe has been updated with new wellness features.', type: 'system', isRead: true, createdAt: '2026-03-18T07:00:00' },
];

export const MOCK_WELLNESS: WellnessCheckin[] = [
  { id: 'w-1', userId: 'user-student-1', date: '2026-03-18', mood: 3, energy: 3, stress: 4 },
  { id: 'w-2', userId: 'user-student-1', date: '2026-03-19', mood: 4, energy: 4, stress: 3 },
  { id: 'w-3', userId: 'user-student-1', date: '2026-03-20', mood: 2, energy: 2, stress: 5 },
  { id: 'w-4', userId: 'user-student-1', date: '2026-03-21', mood: 3, energy: 3, stress: 4 },
  { id: 'w-5', userId: 'user-student-1', date: '2026-03-22', mood: 4, energy: 5, stress: 2 },
  { id: 'w-6', userId: 'user-student-1', date: '2026-03-23', mood: 5, energy: 4, stress: 2 },
  { id: 'w-7', userId: 'user-student-1', date: '2026-03-24', mood: 4, energy: 4, stress: 3 },
];

export const MOCK_CREDENTIALS: Record<string, string> = {
  'student@demo.com': 'student',
  'admin@demo.com': 'admin',
  'coach@demo.com': 'coach',
  'club@demo.com': 'club',
  'teacher@demo.com': 'teacher',
  'it@demo.com': 'it',
  'parent@demo.com': 'parent',
};
