/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        "surface-tint": "#0047AB",
        "surface-container": "#e7e8eb",
        "surface-container-high": "#e1e2e6",
        "secondary-fixed": "#ffc4b1",
        "primary-fixed-dim": "#6390f7",
        "on-secondary-container": "#832800",
        "on-surface-variant": "#5a5c5e",
        "inverse-on-surface": "#9c9d9f",
        "primary-container": "#759eff",
        "surface": "#f6f6f9",
        "tertiary": "#006941",
        "surface-container-lowest": "#ffffff",
        "outline": "#757779",
        "secondary": "#FF7F50",
        "tertiary-container": "#7bfeb8",
        "primary-dim": "#003b8e",
        "surface-container-low": "#f0f0f3",
        "surface-container-highest": "#dbdde0",
        "primary": "#0047AB",
        "secondary-container": "#ffebd9",
        "on-surface": "#2d2f31",
        "surface-dim": "#d2d4d8",
        "primary-fixed": "#759eff",
        "on-primary": "#f0f2ff",
        "on-primary-container": "#001f55",
        "on-secondary": "#ffefeb",
        "on-background": "#2d2f31",
        "background": "#f6f6f9",
        "outline-variant": "#acadaf",
      },
      fontFamily: {
        headline: ['Lexend', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['"Plus Jakarta Sans"', 'sans-serif'],
        lexend: ['Lexend', 'sans-serif'],
        inter: ['Inter', 'sans-serif'],
        jakarta: ['"Plus Jakarta Sans"', 'sans-serif'],
      },
      borderRadius: {
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      boxShadow: {
        float: '0 10px 40px rgba(26,29,46,0.06)',
        rise: '0 16px 48px rgba(26,29,46,0.10)',
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
  ],
};
