/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        // Light mode tokens
        "surface-tint": "#0047AB",
        "surface-container": "#e7e8eb",
        "surface-container-high": "#e1e2e6",
        "secondary-fixed": "#ffc4b1",
        "primary-fixed-dim": "#6390f7",
        "on-secondary-container": "#832800",
        "on-surface-variant": "#5a5c5e",
        "inverse-on-surface": "#9c9d9f",
        "primary-container": "#D6E4FF",
        "surface": "#f6f6f9",
        "tertiary": "#00A86B",
        "surface-container-lowest": "#ffffff",
        "outline": "#757779",
        "secondary": "#FF7F50",
        "tertiary-container": "#C8F5DC",
        "primary-dim": "#003b8e",
        "surface-container-low": "#f0f0f3",
        "surface-container-highest": "#dbdde0",
        "primary": "#0047AB",
        "secondary-container": "#FFE8DE",
        "on-surface": "#2d2f31",
        "surface-dim": "#d2d4d8",
        "primary-fixed": "#759eff",
        "on-primary": "#FFFFFF",
        "on-primary-container": "#001849",
        "surface-lowest": "#FFFFFF",
        "on-primary-cont": "#001849",
        "on-tert-cont": "#002114",
        "on-sec-cont": "#3A1500",
        "on-secondary": "#FFFFFF",
        "on-background": "#2d2f31",
        "background": "#f6f6f9",
        "outline-variant": "#acadaf",
        "error": "#b31b25",
        "error-container": "#fb5151",
        "on-error": "#ffefee",
        "on-error-container": "#570008",
        "inverse-primary": "#6995fd",
        "inverse-surface": "#0c0e10",
        "tertiary-fixed": "#7bfeb8",
        "on-tertiary": "#FFFFFF",
        "tertiary-dim": "#005c38",
        "secondary-fixed-dim": "#ffb196",
      },
      fontFamily: {
        headline: ['Lexend', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['"Plus Jakarta Sans"', 'sans-serif'],
        lexend: ['Lexend', 'sans-serif'],
        inter: ['Inter', 'sans-serif'],
        jakarta: ['"Plus Jakarta Sans"', 'sans-serif'],
      },
      borderRadius: {
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      boxShadow: {
        float: '0 10px 40px rgba(26,29,46,0.06)',
        rise: '0 16px 48px rgba(26,29,46,0.10)',
        lift: '0 8px 24px rgba(26,29,46,0.08)',
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
  ],
};
